import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components";
import ThemeScript from "./theme-script";
import { ThemeProvider } from "@/theme/theme-provider";
import { getDictionary } from "@/i18n/get-disctionary";
import { cookies } from "next/headers";
import { Locale } from "@/i18n/config";
import { I18nProvider } from "@/i18n/dictionary-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const locale = (cookieStore.get("NEXT_LOCALE")?.value as Locale) || "en";
  const dict = await getDictionary(locale);

  return (
    <html lang="en" data-theme="dark" dir="rtl">
      <head>
        <ThemeScript />
      </head>
      <I18nProvider initialLocale={locale} initialDictionary={dict}>
        <ThemeProvider>
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
            <Navbar />

            {children}
          </body>
        </ThemeProvider>
      </I18nProvider>
    </html>
  );
}
